### Deacon's Quiche (Frittata)

Prep and cooking time is about 30 minutes.

#. Using a 13x9 baking dish sprayed with olive oil (could use butter or PAM) place
7 slices of bread either cubed or whole. Lay flat in baking dish with about an inch along the sides.
Moisten bread with a small amount of water. Season with salt and pepper.

#. In a deep skillet, warm 1 tablespoon of EVOO, add 4 chopped plum tomatoes.
I used 1 teaspoon of fresh ground ginger (powder is fine) and some fresh ground pepper.

#. Steam tomatoes until they are mushy.

#. Add 16 ozs of each of
   - frozen peas/carrots
   - frozen chopped spinach and salt to taste

#. Stir together until all ingredients are warm. Add 4 eggs, 4 ozs of milk (whole milk or cream)

#. Fully combine all ingredients.

#. Pour/spoon this hot mix over the moistened bread crust.

#. Optionally, spreading grated cheese on top of quiche

#. Bake at 400 degrees for about 20 minutes.

Let cool for 15 mins and is ready to serve.
